[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
permadata_program = "BYRRLvZyzxLnfoaqea3pL9zY24S6Xd2uvoDHXFiw7LMq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
